version: '3.8'

services:
  frontend-jenkins:
    build: ./my-app
    ports:
      - '3001:3000'  # mapped to a different host port (to avoid conflict)
    depends_on:
      - backend-jenkins

  backend-jenkins:
    build: ./server
    ports:
      - '5001:5000'  # different host port
